### PR TITLE
Add Data Attributes

### PR DESCRIPTION
**Pull request by michaelwehrley**
Add Data Attributes

* Add `data` and  attributes on button and anchor tags.
* Include page `title` attribute.

[Finishes: #94539354]

### CODE REVIEW

**Comment by ericcf** [comment]
My only comment is that you seem to be repeating yourself with the metadata. They all begin with "click ...". Any reason not to strip that out to reduce clutter a little?

**Comment by michaelwehrley** [comment]
Oh I didn't even notice.  I guess I was just trying to achieve readability.  Good catch.  Thanks.

**Comment by michaelwehrley** [comment]
@ericcf I took another stab at it. :hocho: Thanks.

**Comment by ericcf** [comment]
:meat_on_bone:

**Pull request merged**
